version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'Installing Terraform ...'
     # - apt install unzip -y
     # - wget https://releases.hashicorp.com/terraform/1.6.2/terraform_1.6.2_linux_amd64.zip     # Terraform arhīva instalācija
     # - unzip terraform_1.6.2_linux_amd64.zip                                                   # 
     # - mv terraform /usr/local/bin/                                                            # 
     # - terraform init                                                                            # Terraform inicializācija
      - echo 'Terraform initialized successfully!'
      - echo 'Logging into ECR ...'
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 242611965122.dkr.ecr.eu-west-1.amazonaws.com    # ECR autentifikācija un docker ielogošana
     # - terraform validate                                                                            # Terraform validācija
      - echo "Terraform is valid!"
  build:
    on-failure: ABORT
    commands:
      - echo "Provisioning Terraform resources ..."
     # - terraform plan                                                             # Terraform planošana
     # - terraform apply -auto-approve                                              # Terraform instrukciju pielietošana
      - echo "Starting docker build"
      - docker build -t laravel-app-ecr-repo .                                     # Docker konteinera būvešana
      - docker tag laravel-app-ecr-repo:latest 242611965122.dkr.ecr.eu-west-1.amazonaws.com/laravel-app-ecr-repo:latest
      - docker push 242611965122.dkr.ecr.eu-west-1.amazonaws.com/laravel-app-ecr-repo:latest      # Uzbūvēta konteinera izvietošana ECR repozitorijā
  post_build:
    on-failure: ABORT
    commands:
      - echo "Docker images successfully built!"


