version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
  pre_build:
    on-failure: ABORT
    commands:
      - apt install unzip -y
      - wget https://releases.hashicorp.com/terraform/1.6.2/terraform_1.6.2_linux_amd64.zip
      - unzip terraform_1.6.2_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform init
      - echo 'Logging into ECR ...'
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 242611965122.dkr.ecr.eu-west-1.amazonaws.com
      - terraform validate
  build:
    on-failure: ABORT
    commands:
      - terraform plan -var "access_key=${ACCESS_KEY}" -var "secret_key=${SECRET_KEY}"
      - terraform apply -var "access_key=${ACCESS_KEY}" -var "secret_key=${SECRET_KEY}" -auto-approve
      - cp .env.prod .env
      - docker build -t laravel_app_ecr_repo .
      - docker tag laravel_app_ecr_repo:latest 242611965122.dkr.ecr.eu-west-1.amazonaws.com/laravel_app_ecr_repo:latest
  post_build:
    on-failure: ABORT
    commands:
      - docker images ls -a
      - docker push 242611965122.dkr.ecr.eu-west-1.amazonaws.com/laravel_app_ecr_repo:latest
      - echo Writing image definitions file...


