version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
  pre_build:
    on-failure: ABORT
    commands:
      - apt install unzip -y
      - wget https://releases.hashicorp.com/terraform/1.6.2/terraform_1.6.2_linux_amd64.zip
      - unzip terraform_1.6.2_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform init
  build:
    on-failure: ABORT
    commands:
      - cp .env.prod .env
      - docker build -t $IMAGE .
      - docker tag $IMAGE:latest $REPO/$IMAGE:latest
  post_build:
    on-failure: ABORT
    commands:
      - docker images ls -a
      - docker push $REPO/$IMAGE:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE $REPO:latest > imagedef.json
artifacts:
    files: imagedefinitions.json

